return req.json() result, not req.json method
required to fix problem:

Traceback (most recent call last):
  File "/usr/local/bin/bugh", line 52, in <module>
    clone_repos(user_repos(sys.argv[1]))
  File "/usr/local/bin/bugh", line 32, in clone_repos
    for repo in repos:
TypeError: 'instancemethod' object is not iterable